Revert "Bump django-storages from 1.8 to 1.9.1"
This reverts commit 54108b019af82aeedc1e7e81e2effe968b0925a9.

This caused an error in jenkins:

packages/django/core/files/storage.py", line 270, in _save
    for chunk in content.chunks():
  File "/var/www/plexus/releases/blue/plexus/ve/lib/python3.6/site-packages/django/core/files/base.py", line 55, in chunks
    self.seek(0)
ValueError: seek of closed file